// ============================================================
// Raw data types — what the backend tracing engine produces
// ============================================================

export type NodeType = 'thought' | 'tool' | 'citation'

export type ShieldSeverity = 'safety' | 'guideline' | 'correctness' | 'traceability'

export type PruneSource = 'shield' | 'doctor'

/**
 * Where in the reasoning pipeline a compliance check fires.
 * preflight: gateway checks before any diagnostic reasoning begins (PII, allergy, medication screen)
 * terminal:  safety checks at branch endpoints before committing a recommendation (contraindications, drug interactions)
 * cross_cutting: protocol compliance validated over completed branches — not tree nodes, handled as a validation pass
 */
export type ComplianceCheckType = 'preflight' | 'terminal' | 'cross_cutting'

export type ComplianceResult = 'pass' | 'fail' | 'warning'

/**
 * A single node from the tracing engine's flat output.
 * The backend sends an array of these; parent_id references build the tree.
 */
export interface TreeNode {
  id: string
  parent_id: string | null // null for root node
  branch_id: string // 'primary' for the main path, unique id for each branch
  type: NodeType
  headline: string // short 3-8 word summary for compact tree view — shown in collapsed card; content shown in detail panel
  content: string // the reasoning text, tool description, or citation text
  source?: string // for citation/tool nodes: guideline ref, db name, etc.
  source_author?: string  // citation author(s) — e.g. "Beaty JH, Kasser JR (eds)"
  source_chapter?: string // chapter title or number — e.g. "Ch. 17 — Lateral Condyle Fractures"
  source_pages?: string   // page range — e.g. "pp. 714–726"
  is_decision_point: boolean
  // First reasoning node — where clinical thinking begins after preflight clears.
  // Rendered with expanded layout showing patient context + reasoning direction.
  is_reasoning_start?: boolean
  patient_context_summary?: string  // compact demographics + chief complaint line
  patient_vitals_summary?: string   // compact vitals line (BP, HR, SpO₂)
  // Compliance check fields — present on nodes generated by the preflight/terminal safety gates
  is_compliance_check?: boolean
  compliance_check_type?: ComplianceCheckType
  compliance_result?: ComplianceResult   // 'fail' halts reasoning; 'warning' proceeds with caveat
  is_pruned: boolean
  pruned_by: PruneSource | null
  prune_reason: string | null
  shield_severity?: ShieldSeverity // present if flagged by shield model
  shield_checked?: boolean // true if the shield model ran a check on this node (pass or fail)
  children: string[] // ids of child nodes
  diagnosis: string | null // populated on terminal nodes only
  // Terminal node fields — rendered as TerminalCard instead of TreeNode
  terminal_summary?: string     // 1-2 sentence rationale for why the branch reached this diagnosis
  next_step?: string            // suggested action if this branch's conclusion is correct
  terminal_contradiction?: string // if present, the beam found evidence contradicting this hypothesis — shown as "not supported" in synthesis
  path_label?: string           // e.g. "Path 1: Sequential cardiac evaluation"
  terminal_safety_checks?: Array<{ label: string; status: 'pass' | 'warn' | 'fail' | 'flag' }>
  // Architecture-view metadata (hidden in clinical view)
  tool_name?: string // for tool nodes: which tool was called
  result_summary?: string // for tool nodes: what the call returned (1-2 sentences)
  latency_ms?: number // for tool nodes: how long the call took
  step_index?: number // sequential position in the reasoning chain
}

// ============================================================
// Positioned types — after transformer processes the raw data
// ============================================================

/**
 * A node with pixel coordinates assigned by d3-hierarchy layout.
 * This is what React components receive for rendering.
 */
export interface PositionedNode extends TreeNode {
  x: number // pixel x (left edge of node card)
  y: number // pixel y (top edge of node card)
  width: number // node card width in px
  height: number // node card height in px
  depth: number // tree depth (0 = root)
  isOnPrimaryPath: boolean // true if this node is on the primary branch
  isTerminal: boolean // true if no children and diagnosis is populated — renders as TerminalCard
}

/**
 * A connection between two nodes, with pre-computed SVG path data.
 */
export interface Connection {
  id: string // unique id: `${source.id}->${target.id}`
  sourceId: string
  targetId: string
  sourceBranchId: string
  targetBranchId: string
  isOnPrimaryPath: boolean
  pathData: string // SVG path `d` attribute (bezier curve)
  // Fan-in connection from a preflight compliance check to the first reasoning node.
  // These replace the linear chain connections between preflight nodes.
  isPreflightFanIn?: boolean
  complianceResult?: ComplianceResult // carries result so connections can be colored
}

/**
 * A convergence group: multiple branches that reach the same diagnosis.
 */
export interface Convergence {
  diagnosis: string
  branchIds: string[] // which branches converge on this
  terminalNodeIds: string[] // the terminal nodes for each branch
}

/**
 * The full positioned tree — everything the UI needs to render.
 */
export interface PositionedTree {
  nodes: PositionedNode[]
  connections: Connection[]
  convergences: Convergence[]
  primaryPathNodeIds: string[] // ordered list of node ids on the primary path
  branchIds: string[] // all unique branch ids
}

// ============================================================
// Synthesis types — derived from tree state for the right panel
// ============================================================

/**
 * Top-level synthesis: the overall recommendation + confidence.
 * This is the "headline" section of the synthesis panel.
 */
export interface SynthesisData {
  recommendation: {
    diagnosis: string
    summary: string
    supportingNodeIds: string[]
    nextStep?: string // suggested next action for the top-level recommendation
  }
  confidence: {
    level: 'high' | 'moderate' | 'low'
    convergenceRatio: number
    totalBranches: number
    convergingBranches: number
    explanation: string
  }
  branches: BranchSummary[]           // every active branch summary (used internally)
  hypothesisGroups: HypothesisGroup[] // branches grouped by terminal diagnosis
  rejectedPaths: RejectedPath[]
  safetySummary: SafetySummary
}

/**
 * A hypothesis group: all branches that reached the same terminal diagnosis.
 * This is the primary unit of organization in the synthesis panel.
 * Multiple branches converging = higher confidence signal.
 */
export interface HypothesisGroup {
  diagnosis: string
  tag: 'PRIMARY' | 'DIVERGENT' | 'UNLIKELY' | 'CONTRADICTED'
  branchIds: string[]              // all active branches reaching this diagnosis
  pathCount: number                // how many branches
  totalPaths: number               // total active (unpruned) branches
  rationale: string                // 1-2 sentences: why this hypothesis was reached
  branches: BranchSummary[]        // full branch summaries for expanded detail view
  evidenceFor: EvidenceEntry[]     // citations + tool results supporting this dx
  evidenceAgainst: EvidenceEntry[] // competing reasoning + conditions that weaken dx
  nextStep?: string                // suggested investigative action (absent for CONTRADICTED)
  whyNotSupported?: string         // for CONTRADICTED: specific reason the beam found evidence against this
  safetyFlags?: Array<{ label: string }> // patient-safety flags on the terminal node — shown as amber card in synthesis
}

/**
 * A single evidence item — one bullet in the EVIDENCE FOR / AGAINST sections.
 * Clicking it dispatches PEEK_NODE, panning to the source node while
 * keeping all hypothesis branches highlighted.
 */
export interface EvidenceEntry {
  nodeId: string        // for PEEK_NODE dispatch
  headline: string      // concise one-line description
  source: string | null // formal source name, tool name, or competing path label
}

/**
 * A synthesized summary of a single branch.
 * Each branch gets a card in the synthesis panel. The card is clickable
 * (focuses the branch in the tree) and contains node-level summaries.
 */
export interface BranchSummary {
  branchId: string
  isPrimary: boolean
  diagnosis: string | null           // terminal node's diagnosis
  convergsWith: string | null        // if this branch converges with another, which diagnosis
  narrativeSummary: string           // 1-2 sentence plain-language summary of the branch's reasoning
  keyDecision: string | null         // what judgment call launched this branch
  decisionNodeId: string | null      // the decision point node that forked to this branch
  nodeSummaries: NodeSummary[]       // ordered summaries of notable nodes on this branch
  caveat: Caveat | null              // if this branch diverges, what condition would make it correct
}

/**
 * A synthesized summary of a single node within a branch.
 * Shown inside a BranchSummary card. Clickable (selects the node in the tree).
 * Supports doctor actions: flag, annotate, challenge.
 */
export interface NodeSummary {
  nodeId: string
  type: NodeType
  headline: string                   // short summary of what this node does/says (1 line)
  detail: string                     // fuller explanation (shown on expand)
  source: string | null              // citation or tool source, if any
  isKeyStep: boolean                 // true for steps that significantly drive the reasoning
  shieldFlag: ShieldSeverity | null  // non-null if the shield flagged this node
  isDiagnosis?: boolean              // true for the terminal diagnosis node — rendered as conclusion card
}

export interface Caveat {
  condition: string
  implication: string
  sourceNodeId: string
  sourceBranchId: string
}

export interface RejectedPath {
  branchId: string
  diagnosis: string | null
  pruneSource: PruneSource
  pruneReason: string
  shieldSeverity?: ShieldSeverity
  guidelineRef?: string | null  // extracted from prune_reason for shield violations
  terminalNodeId: string
}

// ============================================================
// Safety & compliance summary — for the SafetyComplianceSection
// ============================================================

/**
 * A single affirmative safety check that passed — shown as a ✓ line
 * in the collapsed safety summary.
 */
export interface SafetyCheck {
  nodeId: string        // click → peek at this node in tree
  label: string         // what was checked (node headline)
  source: string | null // DB / guideline that validated this
  // pass = clean green; info = noted but safe (blue); warn = genuine concern (amber)
  status: 'pass' | 'info' | 'warn'
}

/**
 * A safety violation — a branch that was terminated by the shield model.
 * Richer than RejectedPath: includes extracted guideline reference.
 */
export interface SafetyViolation {
  branchId: string
  diagnosis: string | null
  severity: ShieldSeverity
  violation: string        // prune_reason text
  guidelineRef: string | null // extracted section reference (e.g. "ACC/AHA §6.1")
  terminalNodeId: string
}

/**
 * Full safety summary — everything the SafetyComplianceSection needs.
 * Reframes safety from "here's what failed" to "here's the full picture".
 */
export interface SafetySummary {
  passedPaths: number         // active branches (not shield-terminated)
  totalPaths: number          // active + shield-terminated (excludes doctor-pruned)
  flaggedPaths: number        // active branches with at least one 'flag'-status safety check
  passedChecks: SafetyCheck[] // affirmative checks, ordered by relevance
  violations: SafetyViolation[]
}

// ============================================================
// Doctor annotation types — actions the doctor takes on nodes/branches
// ============================================================

export type DoctorAnnotationType = 'flag' | 'context' | 'challenge' | 'pin'

/**
 * A doctor's annotation on a specific node.
 * Created via the synthesis panel's interactive node summaries.
 * Visible in the tree as a badge/indicator on the annotated node.
 */
export interface DoctorAnnotation {
  id: string
  nodeId: string
  type: DoctorAnnotationType
  content: string                    // the doctor's note, question, or flag reason
  createdAt: number                  // timestamp for ordering
}

/**
 * Flag: "I think this reasoning step is wrong/suspicious"
 *   → Node gets a doctor-flag badge in the tree (distinct from shield flags)
 *   → Synthesis panel shows the flag inline on that node's summary
 *
 * Context: "The patient also mentioned X" / "I have additional information"
 *   → Node gets a context badge in the tree
 *   → The added context is shown in the node detail panel
 *   → If backend supports it, downstream reasoning could be re-triggered
 *
 * Challenge: "I disagree with this interpretation"
 *   → Node gets a challenge badge
 *   → If backend supports it, could trigger re-reasoning from this point
 *   → Even without backend support, it's logged and visible — shows the doctor has agency
 *
 * Pin (branch-level): "This is the branch I think is correct"
 *   → Branch gets a pin indicator
 *   → Synthesis panel reorders to show pinned branch first
 *   → Confidence section notes the doctor's endorsement
 */

// ============================================================
// UI state types — Focus, Growth, and Interaction
// ============================================================

export type ViewMode = 'clinical' | 'architecture'

/**
 * Focus state: which branch and node the user is looking at.
 * 
 * IDLE: nothing selected, full tree visible at 100% opacity.
 * BRANCH_FOCUSED: an entire branch is highlighted (root → terminal),
 *   everything else fades to 20-30% opacity.
 *   selectedNodeId may be null (branch focused, no specific node)
 *   or a node id (specific node within the branch is active).
 */
export type FocusState =
  | { mode: 'idle' }
  | {
      mode: 'branch_focused'
      branchId: string
      branchNodeIds: string[]       // ordered root → terminal, for scrubber/navigation
      selectedNodeId: string | null // null = branch highlighted, no specific node
      selectedNodeIndex: number     // position in branchNodeIds (for scrubber)
    }
  | {
      mode: 'hypothesis_focused'
      diagnosis: string               // the terminal diagnosis all branches share
      branchIds: string[]             // all branches reaching this diagnosis
      highlightedNodeId: string | null // evidence item clicked — panned to, visually selected
    }

/**
 * A single beat in the pre-built animation sequence.
 * Each beat is a complete snapshot of tree visibility at that moment.
 */
export interface AnimationBeat {
  /** All node IDs that should be visible at this beat (cumulative) */
  visibleIds: string[]
  /**
   * Which branch IDs are "active" (full opacity).
   * null = all branches at full opacity (trunk / idle phase).
   * Non-null = branches NOT in this list render at 35% opacity.
   */
  activeBranchIds: string[] | null
  /**
   * How long (ms) to hold this beat before auto-advancing.
   * Only used when autoPause is false or after the user resumes.
   */
  pauseMs: number
  /**
   * If true, the growth timer will NOT auto-advance from this beat.
   * The presenter must press Space/Resume to continue.
   * Used at decision points and the convergence moment.
   */
  autoPause?: boolean
  /** Marks this beat as a decision-point reveal (triggers pulse animation on the dp node) */
  isDecisionReveal?: boolean
  /**
   * True on beats that reveal one sibling branch node sequentially after a
   * decision point. Camera pans gently to each node at decision zoom so the
   * audience sees each option before the system commits to a path.
   */
  isBranchReveal?: boolean
  /**
   * True on the first beat that follows a *-beams simultaneous reveal.
   * Triggers a two-step camera: briefly zoom out to show the fork context,
   * then zoom in tight onto the chosen path's first node.
   */
  isFirstAfterFork?: boolean
  /** Debug / voiceover label */
  phase?: string
}

/**
 * Growth playback state: controls the incremental tree-growing animation.
 *
 * Uses a pre-built AnimationBeat sequence instead of a cursor index.
 * Each beat specifies exactly which nodes are visible and which branches are active.
 *
 * Growth auto-pauses at beats where autoPause is true.
 * The presenter clicks resume (or presses space) to continue.
 * While paused, the presenter can click nodes to explore (paused_exploring),
 * which activates the normal focus/navigation system on the already-rendered nodes.
 */
export type GrowthPlaybackState =
  | { mode: 'idle' }
  | {
      mode: 'playing'
      beatIndex: number
      sequence: AnimationBeat[]
    }
  | {
      mode: 'paused_at_decision'
      beatIndex: number
      sequence: AnimationBeat[]
      decisionNodeId: string
    }
  | { mode: 'paused_manual'; beatIndex: number; sequence: AnimationBeat[] }
  | { mode: 'paused_exploring'; beatIndex: number; sequence: AnimationBeat[]; previousFocusMode: 'paused_at_decision' | 'paused_manual' }

// ============================================================
// Audit trail — log of every system and doctor action
// ============================================================

export interface AuditEntry {
  id: string
  timestamp: number
  type: 'system' | 'shield' | 'doctor'
  summary: string
  detail: string | null
  nodeId: string | null
  branchId: string | null
}

/**
 * Full tree UI state — passed through TreeContext.
 */
export interface TreeUIState {
  tree: PositionedTree
  focusState: FocusState
  prunedBranchIds: Set<string>
  pruneSourceMap: Map<string, PruneSource>
  viewMode: ViewMode
  growth: GrowthPlaybackState
  annotations: DoctorAnnotation[]       // all doctor annotations across the tree
  pinnedBranchId: string | null          // doctor-endorsed branch (at most one)
  auditLog: AuditEntry[]
}

/**
 * All possible actions for the tree state reducer.
 */
export type TreeAction =
  // Focus actions
  | { type: 'SELECT_NODE'; nodeId: string }
  | { type: 'FOCUS_BRANCH'; branchId: string }
  | { type: 'FOCUS_HYPOTHESIS'; diagnosis: string; branchIds: string[] }
  | { type: 'PEEK_NODE'; nodeId: string } // highlight a node within hypothesis_focused (pan + select glow)
  | { type: 'NAVIGATE_NEXT' }
  | { type: 'NAVIGATE_PREV' }
  | { type: 'NAVIGATE_SIBLING_BRANCH'; direction: 'up' | 'down' }
  | { type: 'CLEAR_FOCUS' }
  // Pruning
  | { type: 'PRUNE_BRANCH'; branchId: string; source: PruneSource }
  | { type: 'RESTORE_BRANCH'; branchId: string }
  // Doctor annotations
  | { type: 'ADD_ANNOTATION'; nodeId: string; annotationType: DoctorAnnotationType; content: string }
  | { type: 'REMOVE_ANNOTATION'; annotationId: string }
  | { type: 'PIN_BRANCH'; branchId: string }
  | { type: 'UNPIN_BRANCH' }
  // View mode
  | { type: 'TOGGLE_VIEW_MODE' }
  // Growth playback
  | { type: 'START_GROWTH' }
  | { type: 'PAUSE_GROWTH' }
  | { type: 'RESUME_GROWTH' }
  | { type: 'STEP_FORWARD' }
  | { type: 'STEP_BACKWARD' }
  | { type: 'SKIP_TO_END' }
  // Internal: called by the growth timer, not by user actions directly
  | { type: 'GROWTH_TICK' }
  // Audit
  | { type: 'APPEND_AUDIT'; entry: Omit<AuditEntry, 'id' | 'timestamp'> }
